### PR TITLE
for config, first look in modules, then fallback to DOM

### PR DESCRIPTION
**Pull request by stefanpenner**
needs:

- [ ] properly to be made to work (but conceptually this should work like this)
- [ ] tests

### CODE REVIEW

**Comment by rwjblue** [comment]
Conceptually, I like the approach in https://github.com/ember-engines/ember-engines/pull/494 better for FastBoot support.

**Comment by stefanpenner** [comment]
> Conceptually, I like the approach in #494 better for FastBoot support.

I'll take a look!

**Comment by rwwagner90** [comment]
@rwjblue @stefanpenner is this PR also for fastboot support, like #494 ? I tried #494 in my app and it threw errors because `document` was not defined, because we were in fastboot and it was trying to grab the config from `document`. If there is anything I can do to help test or further along either PR, let me know! I would love to get engines working with fastboot.

**Comment by stefanpenner** [comment]
Yup good call, closing this in-favor of: https://github.com/ember-engines/ember-engines/pull/494

**Comment by rwwagner90** [comment]
@stefanpenner #494 doesn't work for me either, unfortunately :(. Issues with trying to load configs or something from `document` and `document` doesn't exist in fastboot, so it blows up.

**Pull request closed without merging**
