### PR TITLE
Removes useDeprecatedIncorrectCSSProcessing

### LINKED ISSUE #559: drop useDeprecatedIncorrectCSSProcessing
cc @rwjblue we are good to drop this right?

### PR DESCRIPTION
**Pull request by villander**
Fix #559 we are removing this on `0.6.x` version's. Please put a label from `breaking change` on this PR

cc: @stefanpenner @rwjblue @dgeb

### CODE REVIEW

**Comment by stefanpenner** [comment]
We should land this, but let's hold of a touch. I'll try to get usages of this resolved on our end asap.

**Comment by villander** [comment]
@stefanpenner do you have any news about it?

**Comment by stefanpenner** [comment]
@rwjblue just confirmed, we can safely remove this. I'll doit as 0.7.x.

**Comment by stefanpenner** [comment]
released as v0.7.0 🎉

**Pull request merged**
