### PR TITLE
Beginning enforce keyword with warning

### PR DESCRIPTION
**Pull request by villander**
keywords: ['ember-addon', 'ember-engine'] will be used to improve npm searchbility, we are starting with a warning for while #574 

starting way to 1.0 🚀

### CODE REVIEW

**Comment by villander** [comment]
cc: @dgeb I need a help with these tests. I still have some errors on tests/acceptance/lazy-routeable-engine-test.js, can you take a look please? only two tests are missing

**Comment by dgeb** [comment]
@villander ok, I will take a look

**Comment by villander** [comment]
thank you @dgeb

**Comment by villander** [comment]
CI fixed @dgeb 😄

**Comment by dgeb** [comment]
thanks for simplifying this @villander

**Pull request merged**
