### PR TITLE
Removed content no longer  needed because of ember-in-repo-engine

### PR DESCRIPTION
**Pull request by perlun**
These files are already created with the correct content by the blueprint.

### CODE REVIEW

**Comment by mike183** [comment]
Wouldn't these steps still be required when creating a standalone engine? Which doesn't yet have a blueprint.

**Comment by perlun** [comment]
> Wouldn't these steps still be required when creating a standalone engine? Which doesn't yet have a blueprint.

Ah, you might be right. Didn't think about that. 😏 Should we then just change this to be a note saying "you don't need this if you're creating an in-repo-engine" or something to the like?

**Comment by trentmwillis** [comment]
We actually need to cut out most of the stuff from the readme, there is an open issue (which I have meant to get to, but no time): https://github.com/ember-engines/ember-engines/issues/310

**Comment by mike183** [comment]
@trentmwillis Is there much stopping us creating a blueprint for standalone engines?

I know there were previously reasons we didn't have one, but unsure what they were.

**Comment by trentmwillis** [comment]
@mike183 the previous issue was there is no way to install a blueprint globally, thus you'd have to be in an Ember project before being able to use the Engine blueprint. That should be unblocked with the next release of Ember-CLI since it'll allow you to download blueprints (such as for glimmer.js apps). @rwjblue could chime in if there is anything else needed.

**Comment by rwjblue** [comment]
Nope, thats it, we could even start the blueprint now (and it would only be usable with canary until the next beta branch point)...

**Comment by rwjblue** [comment]
There is now a blueprint for stand alone engines (as well as one for in-repo engines).

@mike183 - Can you review this again?

**Comment by perlun** [comment]
@trentmwillis 

> These changes seem good to me. Thanks! And sorry for this taking so long to merge.

No worries! There were good reasons for the delay in this case. 👍

**Pull request merged**
