### PR TITLE
Lazy Engines + FastBoot

### PR DESCRIPTION
**Pull request by trentmwillis**
Hopefully the last of these PRs. Prior work can be seen in https://github.com/ember-engines/ember-engines/pull/418 and https://github.com/ember-engines/ember-engines/pull/444.

Todo:
- [x] Fix any test failures (likely to be some on the build side)
- [x] Add tests for new code paths
- [x] Test with ember-engines.com + fastboot

### CODE REVIEW

**Comment by trentmwillis** [comment]
@rwjblue this is ready for review, though I'd appreciate waiting to merge until I can verify this works in an actual app (testing in the ember-engines.com app).

**Comment by trentmwillis** [comment]
Took less time to test than I thought. The integrations works with ember-engines.com!

**Comment by rwjblue** [comment]
I'll review more thoroughly tomorrow, but I was thinking that this would incorporate the new hooks added to ember-cli-fastboot (in https://github.com/ember-fastboot/ember-cli-fastboot/pull/515) so that engines can provide their config to be used by `FastBoot.config('<engine-name-here>')`. 

@trentmwillis / @kratiahuja - Thoughts?

**Comment by trentmwillis** [comment]
I’m unfamiliar with that hook. But reading it seems odd to me that the config “tree”, isn’t a tree. Additionally, it seems like this means that Engines would always need to check for FastBoot at runtime when attempting to access the config which seems undesirable.

**Comment by rwwagner90** [comment]
Hi @trentmwillis I pulled in your branch into my addon and app and I'm getting an error like this with fastboot: `Error: Could not read config from meta tag with name "ember-journal/config/environment" due to error: ReferenceError: document is not defined`. Do I have something set up incorrectly?

**Comment by kratiahuja** [comment]
@trentmwillis curious to understand how else an app access engine config in fastboot? What if each engine has a different config? I thought we want a way for the engine in fastboot to have access to its config.

**Comment by trentmwillis** [comment]
@kratiahuja the engine's config is inserted into a meta tag, but also generated as a JS module. The JS module can be loaded into the fastboot sandbox if needed but is not present in the browser. This is the approach we currently take for loading the `asset-manifest.json` in both environments.

**Comment by kratiahuja** [comment]
@trentmwillis how is the app going to access the JS module at runtime?

**Comment by trentmwillis** [comment]
It's defined as a normal module: https://github.com/trentmwillis/ember-engines/blob/49d233151c84e9b8a9fda2038ddaab47ad198603/lib/engine-config-node-module.js#L1

```js
define('{{MODULE_PREFIX}}/config/environment', function() {
```

So when you do `import environment from 'engine-name/config/environment'` it will return the exported value. Since this gets loaded into the sandbox after the normal module (which reads from the DOM), it will get used instead.

**Comment by kratiahuja** [comment]
Ok, I think that should work too. You are basically loading an AMD module with the same name in fastboot. 

The reason we exposed a hook in FastBoot that engines can use is so that you can write the engine config in `package.json` at build time that fastboot then reads. If the config changes only, then only the package.json changes for fastboot v/s the app-fastboot.js. App won't be providing new SHAs for the files to load in the sandbox. Config generally should be allowed to change without source code change.

It's up to ember-engines if they have the above usecase or not. 

cc: @rwjblue

**Comment by rwwagner90** [comment]
@trentmwillis @kratiahuja not sure if you saw my comment, but it sounds like grabbing the config, as you are talking about here, seems to be the issue I am hitting. Could you please advise on how to make this work? 😄

**Comment by rwwagner90** [comment]
@trentmwillis @kratiahuja would either of you be able to point me in the right direction on how to use this without encountering the error I am getting?

**Comment by trentmwillis** [comment]
@rwwagner90 I'd prefer to avoid tackling additional bugs/troubleshooting in this PR. Would be better to wait for this to merge and then open a separate issue if problems persist.

As of right now, I am unsure where we stand in regards to landing this.

**Comment by rwwagner90** [comment]
@trentmwillis I believe it would be best to get this truly working before merging. If my problem is just that how to set it up is undocumented, then perhaps we add documentation as part of this effort? I'm happy to help write things up, but I need to know how to configure it before I can do so.

**Comment by kratiahuja** [comment]
@rwjblue @trentmwillis what is the path forward for landing this? Do we want to use the new hooks from ember-cli-fastboot?

**Comment by rwwagner90** [comment]
I'm still encountering the error I mentioned in the comments, as well. If this is intended to work with fastboot, we probably are missing some docs on how to configure it here. @rwjblue do you know what the issue might be? It seems to be trying to grab the config off of `document`, but `document` is not a thing in fastboot right?

**Comment by devotox** [comment]
Where does this stand in the list of priorities?

at the moment I have this running in a production beta application and it seems stable

**Comment by rwwagner90** [comment]
@devotox could you please enlighten me on how you got this to work? engines and fastboot together are broken for me. Unsure if there are undocumented steps to setup fastboot or not.

**Comment by devotox** [comment]
@rwwagner90 I didn't do anything special. Just used @trentmwillis branch and it works

**Comment by rwwagner90** [comment]
@devotox are you sure? This error happens: `Error: Could not read config from meta tag with name "ember-journal/config/environment" due to error: ReferenceError: document is not defined`.

I would expect that to happen to everyone, as ember-engines is trying to look at `document` and it can't because we're in fastboot.

**Comment by devotox** [comment]
@rwwagner90 first change your lazyLoading configuration to index.js to this (not saying that is the problem but this is how the configuration is set now)

have you tried clearing out your node modules and reinstalling from scratch?

```
	lazyLoading: {
		enabled: true
	},
```

**Comment by rwwagner90** [comment]
@devotox I'm not even using lazy loading. engines and fastboot just flat out don't work together for me. Does it require lazy loading to work?

**Comment by devotox** [comment]
I was just looking at your repo ember journal and your engine says true for
lazy loading

**Comment by rwwagner90** [comment]
@devotox it says false https://github.com/shipshapecode/ember-journal/blob/master/index.js#L8

**Comment by devotox** [comment]
@rwwagner90 ha apologies I don't know where I got that from then. Hmmm could you try it as a lazy loading engine as this is what this pull request fixes.

**Comment by rwwagner90** [comment]
@devotox I'm not sure how lazy loading would help. If you turn off lazy loading does it break yours? I would expect it to be broken for everyone, since it's trying to use `document`. I wouldn't think lazy or not would matter.

**Comment by mike183** [comment]
@rwwagner90 I think this PR only fixes the issue for lazy loaded engines.

**Comment by devotox** [comment]
Hey guys whats needed to get this across the finish line. we do not want this to grow stale and have to open another PR (or do we? set a new record?) 😄

**Comment by devotox** [comment]
@trentmwillis one possible problem could be the use of `fetch`

```
There was an error running your app in fastboot. More info about the error: 
 Error: Could not find module `fetch` imported from `versus/services/api`
    at missingModule (/Users/devonte/Documents/Finkobo/versus/tmp/broccoli_merge_trees-output_path-lVui0TMj.tmp/assets/vendor/loader/loader.js:247:1)
```

**Comment by kratiahuja** [comment]
@devotox I'll bring this up in the next Ember CLI core team meeting that I can attend. Most likely it will be in sometime in Jan 2018 as I am traveling before that. 

cc: @rwjblue could we do a review of this PR?

**Comment by devotox** [comment]
Thank you @kratiahuja.

**Comment by kratiahuja** [comment]
We discussed this in our Ember CLI team meeting. I will take a stab at the PR with creating a new app and see if this PR works with fastboot.

**Comment by villander** [comment]
@kratiahuja do you have any forecast for this to be merge?

**Comment by kratiahuja** [comment]
@villander not yet. I have been busy with some other things but I do plan to test this this month. I will update this issue when I have got a chance or if someone can lend a help, would be great as well.

**Comment by villander** [comment]
@kratiahuja I can help you with this, what do you need to do? Can I call you on the slack to talk?

**Comment by rwwagner90** [comment]
I've still got the same error I've mentioned a few times on here.

**Comment by kratiahuja** [comment]
@villander I need help with testing this branch with a new app using engines + fastboot.

**Comment by villander** [comment]
@kratiahuja I tested this branch and fastboot worked for me.

I created a simple app, that lazy a engine addon, look: https://github.com/villander/ember-engines-demo

**Comment by villander** [comment]
@kratiahuja This branch works perfectly when lazy loading is true, but fails when it is false.  That is, @rwwagner90  claim is real and needs to be corrected. I'll make a fix for this.

**Comment by trentmwillis** [comment]
@villander has fixed this for when lazy loading is false. It needs a rebase (which I'll try to do this weekend), but in the interim, @rwwagner90 think you could try again to see if it works for you?

**Comment by rwwagner90** [comment]
@trentmwillis yeah, I can try it out. My app has changed a lot since I originally tested this out, so I'll throw together a test app to make sure things work.

**Comment by villander** [comment]
@kratiahuja here is the app with fastboot running with this branch: https://github.com/villander/ember-engines-demo

Now we need to fix those errors that you gave in `node-tests` can anyone help with this? @rwwagner90 @devotox

**Comment by mattmarcum** [comment]
Took a stab and just getting the node tests passing by updating the fixture data and disabling eslint where it was failing:  https://github.com/trentmwillis/ember-engines/pull/7

**Comment by rwwagner90** [comment]
I tried for awhile to get this working, but I'm getting errors. Mostly around:
```
Error: Could not find module `blog/engine` imported from `(require)`
```

Not sure if I messed up configuring or if there is something incompatible I am using or what. If other people see this working with fastboot and are sure they are serving from fastboot exclusively, can you please try lazyLoading as true and false and if it works, that should hopefully eventually work for me 👍

**Comment by villander** [comment]
I updated the README which was a little old. trentmwillis#9

Any suggestions on how to tell about fastboot support? @kratiahuja @trentmwillis

**Comment by trentmwillis** [comment]
Tests are passing now. Thanks to @villander and @mattmarcum for working to test and verify everything!

@rwjblue or @kratiahuja should sign off before we merge. One noteworthy change: all Engine builds (regardless of lazy loading or not) will now generate a `engines-dist/engine-name/config/environment.js` file. This is because we need to load that file in FastBoot for both eager and lazy engines. This has some effect on the asset manifest as well (which can be seen [here](https://github.com/ember-engines/ember-engines/pull/494/files#diff-cbca107a8dce41206e275d54b8ca7f30)).

**Comment by villander** [comment]
Any news about this PR at this week's Ember CLI team meeting?

**Comment by villander** [comment]
@kratiahuja any prediction about this PR being merged?

**Comment by villander** [comment]
@rwjblue Is there a prediction of when this will be merge? Is there something catching? I would love to help.

**Comment by rwwagner90** [comment]
Would be awesome to get this in soon, so I can try to use engines again 😄

**Comment by Sweet-Bob** [comment]
Agree :)

**Comment by Duder-onomy** [comment]
FWIW, We are consuming the final [commit](49663de4fc4756ceb4e90292289a991b61449941) from this PR in production now...

**Comment by villander** [comment]
It's working fine @Duder-onomy ? I'm excited to see a new release with that. And attack the other things of ROADMAP

**Comment by villander** [comment]
https://media.giphy.com/media/xT9IgnxYv1zOoxxBTi/giphy.gif

**Comment by Duder-onomy** [comment]
@villander This commit is working fine for us in prod. The only issue I have found is that the `engine.css` is not downloaded until after the ember app loads. I wish that, if entering the app into an async-engine route in fastboot land, we could get the engines css into the head. If I slow down the network connection, the page looks horribly broken until the ember and the engine loads and kicks off that css download.

**Comment by villander** [comment]
@Duder-onomy if you access `http://localhost:4200/?fastboot=false` ( fastboot as false ) this problem with css disappear?

If this is really a issue, we can leave this to next PR

**Comment by rwjblue** [comment]
Thank you for all of your hard work on this @trentmwillis!

**Pull request merged**
