### PR TITLE
[WIP] Backport fixes for v2.9.0-beta.2 / canary usage to v0.3 branch.

### PR DESCRIPTION
**Pull request by rwjblue**
Backports various fixes from master to v0.3 branch, gets compatible with release (2.8), beta (2.9), and canary.

/cc @dgeb

### CODE REVIEW

**Comment by nathanhammond** [comment]
LGTM, nothing we've not already landed, tests pass on 2.8.

**Comment by trentmwillis** [comment]
@nathanhammond not correct. #200 has not yet landed, and needs to be fixed for compatibility with lazy-loading. Since 0.3 doesn't have lazy loading that is not a huge deal here, but we should likely keep implementation consistent.

**Comment by rwjblue** [comment]
Confirmed, marking as WIP for now

**Comment by nathanhammond** [comment]
What's current status here? I've lost the thread.

**Comment by trentmwillis** [comment]
Most of this has now landed via #203 and #220. We should revisit once #200 has been figured out.

**Pull request closed without merging**
