### PR TITLE
Bump ember-asset-loader from 0.6.1 to 1.0.0

### PR DESCRIPTION
**Pull request by SergeAstapov**
this depends on #818 and should unblock https://github.com/ef4/ember-auto-import/pull/512 cc @thoov

### CODE REVIEW

**Comment by SergeAstapov** [comment]
seem like some tweaks need to happen and it's not seamless upgrade, I'll try to look into root cause cc @thoov @runspired

**Comment by meirish** [comment]
:wave: I opened a PR to this branch with an update to the fixtures that fixes the test failures. Check out https://github.com/ember-engines/ember-engines/pull/823

**Comment by SergeAstapov** [comment]
@meirish Thank you! I didn't have time to look into this yet so really appreciate the help

**Comment by meirish** [comment]
No problem! I'm excited to see this and the related PRs land, so was glad to find a place I could help (even if it was small :D).

**Comment by chriskrycho** [comment]
@SergeAstapov mind merging this and cutting a release with it? We LinkedIn folks would be *suuuuuuuper* grateful!

**Comment by SergeAstapov** [comment]
@chriskrycho merged. although I don't have permissions to npm to do the release.

Also, there are couple of clean ups slated for the major - I'll try to address today or tomorrow.

**Comment by SergeAstapov** [comment]
#825 and #824 should be added to release as well

**Comment by runspired** [comment]
I can release tomorrow when I'm back from DTO

**Pull request merged**
