### PR TITLE
[namespacing] update link-to-external-component to be called link-to-external so references to it are not confused

### PR DESCRIPTION
**Pull request by gabrielcsapo**
*Why?*

To get our application ready to codemod to template imports, we are trying to namespace all external addon helpers and components from a previously formatted

```hbs
{{link-to-external ...}
```

to 

```hbs
{{ember-engines::link-to-external ...}
```

*Problem?*

Currently engines exports the component for link-to-external as link-to-external-component. This will force us to reference 

```hbs
{{ember-engines::link-to-external-component ...}
```

Which is confusing as the docs specify a helper called link-to-external.

### CODE REVIEW

**Comment by gabrielcsapo** [comment]
@stefanpenner it looks like the CI failed due to a yarn lock issue? Would you be able to re-run it? I don't have access to that option from my side.

**Comment by rwjblue** [comment]
CI failure doesn't seem to be lock file related:

>  "ENOENT: no such file or directory, lstat '/home/travis/build/ember-engines/ember-engines/tests/dummy/lib/eager-blog/node_modules'".

**Comment by villander** [comment]
CI fixed

**Comment by gabrielcsapo** [comment]
@rwjblue since the CI is fixed, does the change seem okay to merge now?

**Comment by villander** [comment]
@gabrielcsapo do you need help here?

**Comment by gabrielcsapo** [comment]
@villander @rwjblue added the re-export. Sorry for the delay.

**Comment by villander** [comment]
Why we need keep `addon/components/link-to-external-component.js` with re-export @rwjblue ?

**Comment by gabrielcsapo** [comment]
@villander this is considered public as @rwjblue said. Keeping it would maintain forward compatibility for those use cases.

**Comment by villander** [comment]
Ah ok, just for backward compatibility. Sounds good 

LGTM!

**Comment by gabrielcsapo** [comment]
@villander would we be able to merge and release this? ❤️

**Comment by villander** [comment]
Unfortunately I don’t have this privilege 😕

Can you help here @rwjblue?

**Pull request merged**
