### PR TITLE
Fix funnel + merges

### LINKED ISSUE #508: avoidable funnels + merges
https://github.com/ember-engines/ember-engines/blob/8f66b5e3b8089cd53884be49f270cac05f9a3d17/lib/engine-addon.js#L319

is often truthy, when it really isn't needed as `maybeMergeTrees` via `ember-cli/broccoli/merge-trees` will return EMPTY_MERGE_TREES. In this location this internal construct leaks out, and results an un-needed funnel.

This optimization "EMPTY_MERGE_TREES" should likely be made to not leak as it does, but likely a short-term fix is to make `maybeMergeTrees` aware of it, so that downstream code can be made aware.

- [ ] fix
- [ ] see impact (should often-times remove 1 funnel and 1 merge per engine)
- [ ] @rwjblue thoughts?

### PR DESCRIPTION
**Pull request by villander**
It's fix #508 and replace the PR #509 

- [x] Tests

- [x]  Confirm in big app

### CODE REVIEW

**Comment by stefanpenner** [comment]
I can also likely test this weekend.

**Comment by villander** [comment]
@stefanpenner How will you test this? What is the scenario?

**Comment by stefanpenner** [comment]
@villander I was planning on doing it 2 ways:

* confirm by stepping through the code, that it is working as expected
* confirm by running against once of our large apps (that has like 40 engines or so)

Obviously you can't test in our app, but I think any engine app you have access to should be sufficient.

**Comment by stefanpenner** [comment]
I feel pretty good about this PR, so as long as you have also tested it and confirmed the behavior, we can move forward :)

**Comment by villander** [comment]
Yes @stefanpenner make sense for me.

In addition to the unit tests, I've already tested this with ember-engines website (which is using Fastboot as well). So I think we can move forward.

**Comment by stefanpenner** [comment]
awesome, thanks!

**Pull request merged**
