### PR TITLE
Update ember-cli-addon-tests to 0.11.1.

### PR DESCRIPTION
**Pull request by rwjblue**
Fixes issues with ember-data#master.

### CODE REVIEW

**Comment by rwjblue** [comment]
CI is failing against ember-source@beta and canary. Seems like some sort of issue with route dynamic properties.

**Comment by scalvert** [comment]
There's two failing jobs in CI. I haven't dug into them but it'd be nice to get this merged so we can subsequently merge #595

**Comment by villander** [comment]
we can close this ; )

**Comment by dgeb** [comment]
This dependency has already been updated. Closing.

**Pull request closed without merging**
