### PR TITLE
move ember-cli from devDeps to deps

### PR DESCRIPTION
**Pull request by bartocc**
Found thanks to Yarn 2.0 dependencies enforcement (see https://yarnpkg.com/advanced/migration#a-package-is-trying-to-access-another-package-)

### CODE REVIEW

**Comment by bartocc** [comment]
Here is the full error message output from yarn 2

```
A package is trying to access another package without the second one being listed as a dependency of the first one

Required package: ember-cli (via "ember-cli/lib/broccoli/merge-trees")
Required by: ember-engines@npm:0.8.5 (via /Users/julien/my-project/.yarn/cache/ember-engines-npm-0.8.5-c5ccf67b48-2.zip/node_modules/ember-engines/lib/)

Require stack:
- /Users/julien/my-project/.yarn/cache/ember-engines-npm-0.8.5-c5ccf67b48-2.zip/node_modules/ember-engines/lib/engine-addon.js
- /Users/julien/my-project/packages/ember-engines/stores-map/index.js
- /Users/julien/my-project/.yarn/cache/ember-cli-npm-3.15.2-0c7aabe0ee-2.zip/node_modules/ember-cli/lib/models/package-info-cache/package-info.js
- /Users/julien/my-project/.yarn/cache/ember-cli-npm-3.15.2-0c7aabe0ee-2.zip/node_modules/ember-cli/lib/models/package-info-cache/index.js
- /Users/julien/my-project/.yarn/cache/ember-cli-npm-3.15.2-0c7aabe0ee-2.zip/node_modules/ember-cli/lib/models/project.js
- /Users/julien/my-project/.yarn/cache/ember-cli-npm-3.15.2-0c7aabe0ee-2.zip/node_modules/ember-cli/lib/utilities/get-config.js
- /Users/julien/my-project/.yarn/cache/ember-cli-npm-3.15.2-0c7aabe0ee-2.zip/node_modules/ember-cli/lib/utilities/instrumentation.js
- /Users/julien/my-project/.yarn/cache/ember-cli-npm-3.15.2-0c7aabe0ee-2.zip/node_modules/ember-cli/lib/cli/index.js
- /Users/julien/my-project/.yarn/cache/ember-cli-npm-3.15.2-0c7aabe0ee-2.zip/node_modules/ember-cli/bin/ember


Stack Trace and Error Report: /var/folders/68/n8bv6n6979j33wfw3x_0jlrw0000gn/T/error.dump.0874122308935a603f2b21061da83f2c.log
```

**Comment by bartocc** [comment]
Here is the full error message output from yarn 2

```
A package is trying to access another package without the second one being listed as a dependency of the first one

Required package: ember-cli (via "ember-cli/lib/broccoli/merge-trees")
Required by: ember-engines@npm:0.8.5 (via /Users/julien/my-project/.yarn/cache/ember-engines-npm-0.8.5-c5ccf67b48-2.zip/node_modules/ember-engines/lib/)

Require stack:
- /Users/julien/my-project/.yarn/cache/ember-engines-npm-0.8.5-c5ccf67b48-2.zip/node_modules/ember-engines/lib/engine-addon.js
- /Users/julien/my-project/packages/ember-engines/stores-map/index.js
- /Users/julien/my-project/.yarn/cache/ember-cli-npm-3.15.2-0c7aabe0ee-2.zip/node_modules/ember-cli/lib/models/package-info-cache/package-info.js
- /Users/julien/my-project/.yarn/cache/ember-cli-npm-3.15.2-0c7aabe0ee-2.zip/node_modules/ember-cli/lib/models/package-info-cache/index.js
- /Users/julien/my-project/.yarn/cache/ember-cli-npm-3.15.2-0c7aabe0ee-2.zip/node_modules/ember-cli/lib/models/project.js
- /Users/julien/my-project/.yarn/cache/ember-cli-npm-3.15.2-0c7aabe0ee-2.zip/node_modules/ember-cli/lib/utilities/get-config.js
- /Users/julien/my-project/.yarn/cache/ember-cli-npm-3.15.2-0c7aabe0ee-2.zip/node_modules/ember-cli/lib/utilities/instrumentation.js
- /Users/julien/my-project/.yarn/cache/ember-cli-npm-3.15.2-0c7aabe0ee-2.zip/node_modules/ember-cli/lib/cli/index.js
- /Users/julien/my-project/.yarn/cache/ember-cli-npm-3.15.2-0c7aabe0ee-2.zip/node_modules/ember-cli/bin/ember


Stack Trace and Error Report: /var/folders/68/n8bv6n6979j33wfw3x_0jlrw0000gn/T/error.dump.0874122308935a603f2b21061da83f2c.log
```

**Comment by bartocc** [comment]
oh, looks like #693 (opened 9 days before this) and this PR are both failing on travis CI with the same 
```
The `ember try:one` command requires a scenario name to be specified.` error.
```

Last valid Travis CI build is [#1371](https://travis-ci.org/ember-engines/ember-engines/builds/630194667?utm_source=github_status), that ran on 2019-12-29 for PR #690 

Could that be a Travis CI error ?

**Comment by bartocc** [comment]
Looks like `matrix` and `jobs` are aliases and that Travis CI is now complaning about both being present

Capture d’écran 2020-02-27 à 17 48 43

Also looks like `fail_fast` is not documented in Travis CI and should be replaced with `fast_finish`. See  https://github.com/ember-cli/ember-cli/pull/8943

**Comment by bartocc** [comment]
I've created #695 to fix the travis ci config in a separate PR.
I'll rebase this one on master if #695 gets approved

**Comment by bartocc** [comment]
rebased on master since #695 has been merged 👍

**Comment by bartocc** [comment]
Please, let me know if this PR needs more work to be reviewed 🙏

**Comment by villander** [comment]
cc: @dgeb

**Comment by rwjblue** [comment]
Ah wait actually, I don't think this makes sense 🤔

Why would ember-engines depend on ember-cli?

**Comment by bartocc** [comment]
@rwjblue I believe the problem comes from `const mergeTrees = require('ember-cli/lib/broccoli/merge-trees');`  in https://github.com/ember-engines/ember-engines/blob/master/lib/engine-addon.js#L5

If ember-engines does a require on an `ember-cli` file, it should depend on it, right?

**Comment by rwjblue** [comment]
No? ember-engines only runs when ember-cli is present so we don't need to worry about it being missing. In order to satisfy the constraint you hit, I could imagine adding ember-cli as a peer dependency. I'm fairly sure that yarn@2 / Berry allows requires from peer dependencies.

**Comment by bartocc** [comment]
I have not worked on this PR for a while and as far as I cal tell, last time I used yarn2 and ember-cli, I did not hit the issue that I initially reported.

So I'll close this PR.

I'll comeback here if I do hit the issue again in the future.

**Comment by dgeb** [comment]
@bartocc ok, thanks for the update.

**Pull request closed without merging**
